load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
  name = "io_bazel_rules_closure",
  sha256 = "7d206c2383811f378a5ef03f4aacbcf5f47fd8650f6abbc3fa89f3a27dd8b176",
  strip_prefix = "rules_closure-0.10.0",
  urls = [
    "https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/0.10.0.tar.gz",
    "https://github.com/bazelbuild/rules_closure/archive/0.10.0.tar.gz",
  ],
)

local_repository(
  name = "org_tensorflow",
  path = "/tensorflow_src",
)

load("@org_tensorflow//tensorflow:workspace.bzl", "tf_workspace")
tf_workspace(tf_repo_name = "org_tensorflow")

local_repository(
  name="org_mediapipe",
  path = "/mediapipe_src",
)